# Generated by Django 3.0.8 on 2021-01-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('reg_no', models.CharField(default='EU/CS/CSC/19/000', max_length=20)),
                ('prev_allocation', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
