# Generated by Django 3.0.8 on 2021-01-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone', models.IntegerField(db_tablespace=1, default=234, max_length=11)),
                ('username', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(default=None, max_length=200)),
                ('confirm', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
