# Generated by Django 3.0.8 on 2021-02-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.IntegerField(db_tablespace=1, default=234),
        ),
    ]
